# https://github.com/actions/add-to-project#creating-a-pat-and-adding-it-to-your-repository

name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/tommyalmendingen/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: -lev - Accenture,bug
          label-operator: OR
