name: Test JSON Action

on: workflow_dispatch

jobs:
  test:
   runs-on: ubuntu-latest
   name: Extract Payload
   
   steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Issue Body Parser
       uses: peter-murray/issue-body-parser-action@v1
       id: issue_body_parser
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         issue_id: 1
         payload_marker: payload
     
     - name: Use Parsed Values
       env:
         DATA: ${{ steps.issue_body_parser.outputs.payload }}
         CONTENT_VERSION_VALUE: ${{ fromJSON(steps.issue_body_parser.outputs.payload).version }}
       run: >
         echo "$DATA\n"
         echo "VERSION: $CONTENT_VERSION_VALUE\n"
